apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-review-dashboard
spec:
  selector:
    matchLabels:
      app: code-review-dashboard
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: code-review-dashboard
    spec:
      containers:
      - name: code-review-dashboard
        image: gcr.io/ignasi-permanent-ffxxqcd8/code-review-dashboard:0.1
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        envFrom:
         - secretRef:
             name: code-review-dashboard-config
