apiVersion: v1
kind: Service
metadata:
  name: code-review-dashboard
spec:
  type: LoadBalancer
  selector:
    app: code-review-dashboard
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
